// server/src/shared/schema.ts
// Backend version - uses firebase-admin instead of firebase client

import { z } from "zod";
import { Timestamp } from "firebase-admin/firestore";

// ===================================
// Firestore Collection Interfaces
// ===================================

// Stored in the 'users' collection
export interface User {
  id: string; // The Firebase Auth UID
  username: string;
  email: string;
  firstName?: string;
  lastName?: string;
  profileImageUrl?: string;
  bio?: string;
  role: 'user' | 'admin';
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Stored in the 'groups' collection
export interface Group {
  id: string; // Auto-generated by Firestore
  name: string;
  description?: string;
  category?: string;
  privacy: 'public' | 'private';
  creatorId: string; // The UID of the user who created it
  coverImage?: string;
  inviteCode?: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Stored in a subcollection: 'groups/{groupId}/members'
export interface GroupMember {
  id: string; // The UID of the user
  role: 'member' | 'admin' | 'moderator';
  joinedAt: Timestamp;
  name: string;
  profileImageUrl?: string;
}

// Stored in the 'userChats' top-level collection for 1-on-1 DMs
export interface UserChat {
  id: string; // A composite key like 'uid1_uid2'
  participantIds: [string, string];
  lastMessage?: {
    text: string;
    senderId: string;
    timestamp: Timestamp;
  };
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Stored in a subcollection: 'userChats/{chatId}/messages' OR 'groups/{groupId}/messages'
export interface Message {
  id: string; // Auto-generated by Firestore
  content: string;
  senderId: string; // The UID of the sender
  senderName: string;
  senderProfileImageUrl?: string;

  // --- CHANGE START: ADDED FOR CALL LOGS ---
  type?: 'text' | 'file' | 'call-log'; // Differentiates message types
  callId?: string; // Unique ID to track a specific call log message for updates
  // --- CHANGE END ---

  fileUrl?: string;
  fileType?: string;
  fileName?: string;
  fileSize?: number;
  createdAt: Timestamp;
}

// ... (Other interfaces like File, StudySession, Notification remain the same) ...
export interface File {
  id: string;
  name: string;
  description?: string;
  fileUrl: string;
  fileType: string;
  fileSize: number;
  uploaderId: string;
  createdAt: Timestamp;
}

export interface StudySession {
  id: string; // Auto-generated by Firestore
  groupId: string;
  title: string;
  description?: string;
  startTime: Timestamp; // Date and time of the session
  sessionUrl: string; // The URL for the video call (e.g., Google Meet, Zoom)
  creatorId: string;
  creatorName: string; // Denormalized for easy display
  creatorProfileImageUrl?: string; // Denormalized for easy display
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface Notification {
  id: string;
  type: 'group_invite' | 'session_reminder' | 'message';
  message: string;
  isRead: boolean;
  relatedId?: string;
  createdAt: Timestamp;
}

// ===================================
// Zod Schemas for Data Insertion
// ===================================

export const insertUserSchema = z.object({
  id: z.string(),
  username: z.string(),
  email: z.string().email(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  profileImageUrl: z.string().url().optional(),
  bio: z.string().optional(),
  role: z.enum(['user', 'admin']),
});
export type InsertUser = z.infer<typeof insertUserSchema>;



export const insertGroupSchema = z.object({
  name: z.string().min(3, "Group name must be at least 3 characters"),
  description: z.string().optional(),
  category: z.string().optional(),
  privacy: z.enum(['public', 'private']),
  creatorId: z.string(),
  coverImage: z.string().url().optional(),
  inviteCode: z.string().optional(),
});
export type InsertGroup = z.infer<typeof insertGroupSchema>;



export const insertMessageSchema = z.object({
  content: z.string().min(1),
  senderId: z.string(),
  senderName: z.string(),
  senderProfileImageUrl: z.string().url().optional(),

  // --- CHANGE START: ADDED FOR CALL LOGS ---
  type: z.enum(['text', 'file', 'call-log']).optional(),
  callId: z.string().optional(),
  // --- CHANGE END ---

  fileUrl: z.string().url().optional(),
  fileType: z.string().optional(),
  fileName: z.string().optional(),
  fileSize: z.number().optional(),
});
export type InsertMessage = z.infer<typeof insertMessageSchema>;



export const insertGroupMemberSchema = z.object({
  id: z.string(), // The user's UID
  role: z.enum(['member', 'admin', 'moderator']),
  name: z.string(),
  profileImageUrl: z.string().url().optional(),
});
export type InsertGroupMember = z.infer<typeof insertGroupMemberSchema>;

export const insertUserChatSchema = z.object({
  participantIds: z.tuple([z.string(), z.string()]),
});
export type InsertUserChat = z.infer<typeof insertUserChatSchema>;



export const insertStudySessionSchema = z.object({
  groupId: z.string(),
  title: z.string().min(3, "Title must be at least 3 characters"),
  description: z.string().optional(),
  // Note: The client will send a Date object, which will be converted to a Timestamp on the server
  startTime: z.date({ required_error: "Please select a date and time" }), 
  sessionUrl: z.string().url({ message: "Please enter a valid meeting URL" }),
  creatorId: z.string(),
  creatorName: z.string(),
  creatorProfileImageUrl: z.string().url().optional(),
});
export type InsertStudySession = z.infer<typeof insertStudySessionSchema>;
